### ISSUE TITLE
Save inputted music

### ISSUE THREAD

**Issue by Parshana007** [jqueja/WorkoutWhiz#65]
- [ ] Frontend to backend connect
- [ ] Create tables in backend
- [ ] Create login in backend

**Comment by jqueja** [comment]
Working on adding the right tables to the backend
Create the music table,
where each link is associated with a specific user.

Create the following functionality API endpoints.
ADD music to a user
Delete music for a user
Gather all music associated with the user

**Comment by jqueja** [comment]
Estimate: 5 Hours
Actual: 3 Hours
